Leo Malak TP03

#A
SELECT * FROM ARTICLE;

#B
SELECT REF, DESIGNATION FROM ARTICLE WHERE PRIX > 2;

#C
SELECT * FROM ARTICLE WHERE PRIX >= 2 AND PRIX <= 6.25;

#D
SELECT * FROM ARTICLE WHERE PRIX BETWEEN 2 AND 6.25;

#E
SELECT * FROM ARTICLE 
WHERE PRIX NOT BETWEEN 2 AND 6.25 
AND ID_FOU != (SELECT ID FROM FOURNISSEUR WHERE NOM = 'Française d’Imports') 
ORDER BY PRIX DESC;

#F
SELECT * FROM ARTICLE 
WHERE ID_FOU = (SELECT ID FROM FOURNISSEUR WHERE NOM = 'Française d’Imports') 
OR ID_FOU = (SELECT ID FROM FOURNISSEUR WHERE NOM = 'Dubois & Fils');

#G
SELECT * FROM ARTICLE 
WHERE ID_FOU IN (SELECT ID FROM FOURNISSEUR WHERE NOM IN ('Française d’Imports', 'Dubois & Fils', 'FDM SA'));

#H
SELECT * FROM ARTICLE 
WHERE ID_FOU NOT IN ( 
    SELECT ID FROM FOURNISSEUR 
    WHERE NOM IN ('Française d’Imports', 'Dubois & Fils')
);

#I
SELECT * FROM BON 
WHERE DATE_COMMANDE BETWEEN '2019-02-01' AND '2019-04-30';
